In [ ]:
import pandas as pd
import numpy as np
import requests
import json

In [2]:
backups = pd.read_csv("https://raw.githubusercontent.com/datarescueproject/portal/refs/heads/main/baserow_exports/datarescue_backups.csv")
datasets = pd.read_csv("https://raw.githubusercontent.com/datarescueproject/portal/refs/heads/main/baserow_exports/datarescue_datasets.csv")

In [3]:
datasets.columns = datasets.columns.str.lower()
datasets = datasets.fillna('')
datasets.head()

,dataset,notes,dataset_id,url,websites,organization,agency,last_modified
0,Billion-Dollar Weather and Climate Disasters,,1,https://www.ncei.noaa.gov/access/billions/mapping,ncei.noaa.gov,National Oceanic and Atmospheric Administration,Department of Commerce,2025-02-10
1,American Communities Survey (ACS),,3,https://www.census.gov/programs-surveys/acs,census.gov,Census Bureau,Department of Commerce,2025-03-03
2,BLS Downloads,,6,https://download.bls.gov,download.bls.gov,Bureau of Labor Statistics,Department of Labor,2025-02-10
3,CDC FTP,,7,https://ftp.cdc.gov/,ftp.cdc.gov,Centers for Disease Control and Prevention,Department of Health and Human Services,2025-02-10
4,US Census Bureau FTP,,8,ftp://ftp.census.gov,census.gov,Census Bureau,Department of Commerce,2025-02-11

In [4]:
agencies = datasets.agency.value_counts().keys()
categories = categories = ['arts-culture-history','health-human-services',
'budget-finance','parks-recreation','economy','planning-zoning',
'education','public-safety','elections-politics','real-estate-land-records',
'environment','transportation','food','uncategorized']

In [5]:
agency_to_category = {
    'Department of Health and Human Services': 'Health / Human Services',
    'Department of Commerce': 'Economy',
    'Department of Housing and Urban Development': 'Real Estate / Land Records',
    'Department of Veterans Affairs': 'Health / Human Services',
    'National Endowment for the Humanities': 'Arts / Culture / History',
    'AmeriCorps': 'Public Safety',
    'Department of Education': 'Education',
    'Federal Mediation and Conciliation Service': 'Economy',
    'Department of Homeland Security': 'Public Safety',
    'Department of Energy': 'Environment',
    'National Labor Relations Board': 'Economy',
    'Environmental Protection Agency': 'Environment',
    'Consumer Financial Protection Bureau': 'Budget / Finance',
    'Federal Housing Finance Agency': 'Real Estate / Land Records',
    'Department of the Treasury': 'Budget / Finance',
    'Institute of Museum and Library Services': 'Arts / Culture / History',
    'Department of the Interior': 'Parks / Recreation',
    'General Services Administration': 'Economy',
    'Department of Labor': 'Economy',
    'U.S. Agency for International Development': 'Health / Human Services',
    'Department of Transportation': 'Transportation',
    'National Aeronautics and Space Administration': 'Environment',
    '': 'Uncategorized',
    'Department of Justice': 'Public Safety',
    'Department of the Interior, National Parks Service': 'Parks / Recreation',
    'Department of State': 'Elections / Politics',
    'National Science Foundation': 'Education',
    'Department of Health and Human Services, Department of Commerce': 'Health / Human Services',
    'Consumer Financial Protection Bureau, Federal Housing Finance Agency': 'Budget / Finance',
    'U.S. Department of Agriculture': 'Food',
    'Office of Management and Budget': 'Budget / Finance'
}

In [6]:
backups.columns = backups.columns.str.lower()
backups = backups.fillna('')
backups.head()

,dataset,dataset_id,status,url,source_website,organization,agency,download_date,size,maintainer,download_location,file_type,notes,metadata_available,metadata_url
0,Billion-Dollar Weather and Climate Disasters,1,Finished,https://www.ncei.noaa.gov/access/billions/mapping,ncei.noaa.gov,National Oceanic and Atmospheric Administration,Department of Commerce,2025-02-10,0.15,HD,https://dataverse.harvard.edu/dataset.xhtml?pe...,ZIP,,yes,https://dataverse.harvard.edu/dataset.xhtml?pe...
1,BLS Downloads,6,Finished,https://download.bls.gov,download.bls.gov,Bureau of Labor Statistics,Department of Labor,2025-02-01,47.0,DRP,,,,,
2,CDC FTP,7,Finished,https://ftp.cdc.gov/,ftp.cdc.gov,Centers for Disease Control and Prevention,Department of Health and Human Services,2025-02-01,213.0,DRP,,,,,
3,US Census Bureau FTP,8,Finished,ftp://ftp.census.gov,census.gov,Census Bureau,Department of Commerce,2025-02-01,180.0,DRP,,,"Partial download, server is back online but co...",,
4,National Hurricane Center (NHC),9,Finished,https://www.nhc.noaa.gov/archive,nhc.noaa.gov,NOAA/National Hurricane Center,Department of Commerce,2025-02-06,61.0,DRP,,,,,

In [11]:
import re
def slugify(string):
    string = clean_text(string)
    # Remove special characters
    string = re.sub(r'[^\w\s-]', '', string)
    # Replace spaces with hyphens
    string = re.sub(r'\s+', '-', string)
    # Convert to lowercase
    string = string.lower()
    return string

def clean_text(string):
    # Remove URL prefixes like http:// or https://
    # string = re.sub(r'http[s]?://', '', string)
    # Remove escape strings like \n
    string = string.replace('\n', '').replace('\r', '').replace('\t', '')
    # Remove leading '-'
    string = re.sub(r'^-', '', string)
    # Replace ':' with '-'
    string = string.replace(':', '')
    return string

def get_dataset_categories(agency):
    return agency_to_category[agency]

In [8]:
def get_metadata_availability(dataset_id):
    """
    This function checks the metadata availability for dataset_id 432 in the backups dataframe.
    It returns "Yes" if metadata is available, "Under Review" if it needs review, and "No" otherwise.
    """
    md_avl = backups[backups.dataset_id == dataset_id].metadata_available.values
    if "yes" in md_avl:

        return "Yes",backups[backups.dataset_id == dataset_id].metadata_url.values[0]
    elif "needs review" in md_avl:
        return "Under Review",""
    else:
        return "No",""

def create_dataset_md(row):
    if row['organization'] == '':
      row['organization'] = 'Unknown'
    ## Defining the schema, filename and path
    schema = 'data_rescue_project'
    dataset_filename = slugify(row['dataset'])
    dataset_path = "_datasets"
    org_filename = slugify(row['organization'])
    org_path = "_organizations"

    ## Get backups for each dataset
    data_backups = backups[backups.dataset == row['dataset']]
    metadata_available, metadata_url = get_metadata_availability(row['dataset_id'])
    ## Creating the dataset markdown file
    ## Dataset-level information
    dataset_md = "---\n"
    dataset_md += f"schema: {schema} \n"
    dataset_md += f"title: {clean_text(row['dataset'])}\n"
    dataset_md += f"organization: {clean_text(row['organization'])}\n"
    dataset_md += f"agency: {clean_text(row['agency'])}\n"
    dataset_md += f"websites: {row['websites']}\n"
    dataset_md += f"data_source: {row['url']}\n"
    dataset_md += f"description: {clean_text(row['notes'])}\n"
    dataset_md += f"last_modified: {row['last_modified']}\n"
    ## Check if any backups have metadata available and populate
    dataset_md += f"metadata_available: {metadata_available}\n"
    dataset_md += f"metadata_url: {metadata_url}\n"
    dataset_md += f"category:\n"
    dataset_md += f"  - {get_dataset_category(clean_text(row['agency']))}\n"

    dataset_md += f"resources:\n"
    ## Resource-level information
    for index, backup_row in data_backups.iterrows():
      dataset_md += f"  - id: {index}\n"
      dataset_md += f"    url: {backup_row['download_location']}\n"
      dataset_md += f"    format: {clean_text(backup_row['file_type'])}\n"
      dataset_md += f"    status: {clean_text(backup_row['status'])}\n"
      dataset_md += f"    size: {backup_row['size']}\n"
      dataset_md += f"    download_date: {backup_row['download_date']}\n"
      dataset_md += f"    maintainer: {clean_text(backup_row['maintainer'])}\n"
      dataset_md += f"    notes: {clean_text(backup_row['notes'])}\n"
    dataset_md += "---\n"
      
    ## Writing the dataset markdown file
    with open(f'{dataset_path}/{dataset_filename}.md', 'w') as output:
      output.write(dataset_md)
    
    ## Creating the organization markdown file
    org_md = "---\n"
    org_md += f"title: {clean_text(row['organization'])} \n" 
    org_md += f"description: \n" 
    org_md += "---\n"

    ## Writing the organization markdown file
    with open(f'{org_path}/{org_filename}.md', 'w') as output:
      output.write(org_md)

In [9]:
datasets.shape

(731, 8)

In [13]:
datasets.apply(create_dataset_md, axis=1)

0      None
1      None
2      None
3      None
4      None
       ...
726    None
727    None
728    None
729    None
730    None
Length: 731, dtype: object

In [10]:
import os
def remove_files_os(dir_path):
    for filename in os.listdir(dir_path):
        file_path = os.path.join(dir_path, filename)
        if os.path.isfile(file_path):
            os.remove(file_path)

In [5]:
a = []
if not a:
    print("test")

test

In [ ]:
def replace_multiple_spaces(string):
    return re.sub(r'\s+', ' ', string)

# Example usage
example_string = "This   is  a   string    with multiple   spaces."
cleaned_string = replace_multiple_spaces(example_string)
print(cleaned_string)

In [11]:
remove_files_os('_datasets')

In [8]:
def clean_text(string):
    # Remove URL prefixes like http:// or https://
    # string = re.sub(r'http[s]?://', '', string)
    # Remove escape strings like \n
    string = string.replace('\n', '').replace('\r', '').replace('\t', '')
    # Remove multiple spaces
    string = re.sub(r'\s+', ' ', string)
    # Remove leading spl. characters
    string = re.sub(r'^[^a-zA-Z]+', '', string)
    # string = string.lstrip(',')
    string = re.sub(r'^-', '', string)
    # Remove leading and trailing ':'
    string = string.rstrip(':')
    string = re.sub(r'(?<!http)(?<!https):', '', string)
    
    return string

In [9]:
test_string = ",https://www.ncei.noaa.gov/metadata/geoportal/rest/metadata/item/gov.noaa.ncdcC01557/html#"
clean_text(test_string)

'https://www.ncei.noaa.gov/metadata/geoportal/rest/metadata/item/gov.noaa.ncdcC01557/html#'

In [ ]:
test_string = test_string.lstrip(',')
print(test_string)

In [3]:
%load_ext autoreload
%autoreload 2

from create_markdowns import *
import os

In [8]:
def remove_files_os(dir_path):
    for filename in os.listdir(dir_path):
        file_path = os.path.join(dir_path, filename)
        if os.path.isfile(file_path):
            os.remove(file_path)
            
# Remove files in _datasets and _organizations
remove_files_os('../_datasets')
remove_files_os('../_organizations')
remove_files_os('../_dataset_categories')

create_markdowns()

In [5]:
organizations = pd.read_csv("https://raw.githubusercontent.com/datarescueproject/portal/refs/heads/main/baserow_exports/datarescue_organizations.csv")
print(organizations[organizations['Organizations'] == 'National Oceanic and Atmospheric Administration']['Categories'].str.split(';').values[0])
print(organizations[organizations['Organizations'] == 'Department of the Interior']['Categories'].str.split(';').values[0])

['Climate & Environment']
['Climate & Environment', 'Humanitarian & Disaster Relief']

In [6]:
organizations

,Organizations,Categories
0,American Battle Monuments Commission,Arts & Culture
1,Barry Goldwater Scholarship and Excellence in ...,Education
2,Consumer Financial Protection Bureau,Business & Economy
3,Delta Regional Authority,Business & Economy
4,Denali Commission,Business & Economy;Infrastructure
...,...,...
416,Federal Mediation and Conciliation Service,Labor & Employment
417,Health Resources and Services Administration,Health & Healthcare;Social Services
418,Institute of International Education,Education
419,U.S. Patent and Trademark Office,Business & Economy
420,National Center for Education Statistics,Education

In [ ]:
combined_array = organizations.values.flatten()
print(combined_array)

In [6]:
backups = pd.read_csv("https://raw.githubusercontent.com/datarescueproject/portal/refs/heads/main/baserow_exports/datarescue_backups.csv")
datasets = pd.read_csv("https://raw.githubusercontent.com/datarescueproject/portal/refs/heads/main/baserow_exports/datarescue_datasets.csv")
organizations = pd.read_csv("https://raw.githubusercontent.com/datarescueproject/portal/refs/heads/main/baserow_exports/datarescue_organizations.csv")

backups.columns = backups.columns.str.lower()
backups = backups.fillna('')
backups.head()

datasets.columns = datasets.columns.str.lower()
datasets = datasets.fillna('')
datasets.head()

organizations = organizations.fillna('')

In [72]:
datasets = datasets[datasets['dataset'].str.contains("Environmental Justice")]

In [76]:
create_dataset_md(datasets.loc[54],backups, organizations)

In [82]:
row = datasets.loc[54]

In [83]:
if row['organization'] == '':
    row['organization'] = 'Unknown'
# Defining the schema, filename and path
schema = 'data_rescue_project'
dataset_filename = slugify(row['dataset'])
dataset_path = "../_datasets"
org_filename = slugify(row['organization'])
org_path = "../_organizations"

# Get backups for each dataset
data_backups = backups[backups.dataset == row['dataset']]
metadata_available, metadata_url = get_metadata_availability(row['dataset_id'], data_backups)
# Creating the dataset markdown file
# Dataset-level information
dataset_md = "---\n"
dataset_md += f"schema: {schema} \n"
dataset_md += f"title: {clean_text(row['dataset'])}\n"
dataset_md += f"organization: {clean_text(row['organization'])}\n"
dataset_md += f"agency: {clean_text(row['agency'])}\n"
dataset_md += f"websites: {clean_text(row['websites'])}\n"
dataset_md += f"data_source: {clean_text(row['url'])}\n"
dataset_md += f"description: {clean_text(row['notes'])}\n"
dataset_md += f"last_modified: {row['last_modified']}\n"
# Check if any backups have metadata available and populate
dataset_md += f"metadata_available: {metadata_available}\n"
dataset_md += f"metadata_url: {clean_text(metadata_url)}\n"
dataset_md += "category:\n"
cats = get_dataset_category(row, organizations)

for cat in cats:
    dataset_md += f"  - {cat} \n"
    
dataset_md += "resources:\n"
# Resource-level information
for index, backup_row in data_backups.iterrows():
    dataset_md += f"  - id: {index}\n"
    dataset_md += f"    url: {clean_text(backup_row['download_location'])}\n"
    dataset_md += f"    format: {clean_text(backup_row['file_type'])}\n"
    dataset_md += f"    status: {clean_text(backup_row['status'])}\n"
    dataset_md += f"    size: {backup_row['size']}\n"
    dataset_md += f"    download_date: {backup_row['download_date']}\n"
    dataset_md += f"    maintainer: {clean_text(backup_row['maintainer'])}\n"
    dataset_md += f"    notes: {clean_text(backup_row['notes'])}\n"
dataset_md += "---\n"
    
# Writing the dataset markdown file
with open(f'{dataset_path}/{dataset_filename}.md', 'w') as output:
    output.write(dataset_md)

# Creating the organization markdown file
org_md = "---\n"
org_md += f"title: {clean_text(row['organization'])} \n" 
org_md += "description: \n" 
org_md += "---\n"

# Writing the organization markdown file
with open(f'{org_path}/{org_filename}.md', 'w') as output:
    output.write(org_md)

In [79]:
def get_dataset_category(row, organizations):
    # Check if dataset has category override
    categories = eval(row['categories'])
    if categories:
        cats = [a['value'] for a in categories]
    # Check if we don't have organization info
    elif row['organization'] == 'Unknown':
        cats = ['Uncategorized']
    else:
        # Get categories from organization
        cats_from_org = organizations[organizations['Organizations'] == row['organization']]['Categories'].values
        cats = []
        [cats.extend(v.split(';')) for v in cats_from_org]      
        cats = list(set(cats))
        if cats == ['']:
            cats = ['Uncategorized']
        else:
            cats = [cat for cat in cats if cat != '']
    
    return cats

In [80]:
get_dataset_category(datasets.loc[54], organizations)

['Climate & Environment', 'Health & Healthcare']

In [59]:
datasets = datasets[datasets['dataset'].str.startswith('20')]

In [60]:
datasets.apply(create_dataset_md, axis=1, args=(backups, organizations))

393    None
395    None
396    None
397    None
398    None
399    None
400    None
401    None
403    None
404    None
405    None
407    None
408    None
409    None
410    None
416    None
640    None
662    None
663    None
665    None
666    None
667    None
696    None
697    None
698    None
798    None
799    None
dtype: object

In [ ]:
def get_dataset_category(row):
    # Check if dataset has category override
    categories = eval(row['categories'])
    if categories:
        cats = [a['value'] for a in categories]
    # Check if we don't have organization info
    elif row['organization'] == 'Unknown':
        cats = ['Uncategorized']
    else:
        # Get categories from organization
        cats_from_org = organizations[organizations['Organizations'] == row['organization']]['Categories'].values
        cats = []
        [cats.extend(v.split(';')) for v in cats_from_org]      
        cats = list(set(cats))
        if cats == ['']:
            cats = ['Uncategorized']
        else:
            cats = [cat for cat in cats if cat != '']

[None, None]

In [51]:
a = ''
len(a.split(';'))

1

In [9]:
import numpy as np
organizations[organizations['Categories']== np.nan]

Empty DataFrame
Columns: [Organizations, Categories]
Index: []

In [ ]:
BASEROW_ACCESS_TOKEN = 'your_baserow_access_token_here'

def stringify_arr_vals(arr):
    return ';'.join([i['value'] for i in arr])

def get_results_json(url):
    table = requests.get(
        url,
        headers={
            "Authorization": f"Token {BASEROW_ACCESS_TOKEN}"
        }
    )

    res = table.json()['results']
    if table.json()['next'] is not None:
        res.extend(get_results_json(table.json()['next']))

    return res

# categories = pd.DataFrame(get_results_json("https://baserow.datarescueproject.org/api/database/rows/table/732/?user_field_names=true"))[['Name', 'Active']]
# organizations = pd.DataFrame(get_results_json("https://baserow.datarescueproject.org/api/database/rows/table/638/?user_field_names=true"))[['Organizations', 'Categories']]
# organizations['Categories'] = organizations['Categories'].apply(lambda x: stringify_arr_vals(x))
# categories.to_csv("baserow_exports/datarescue_categories.csv", index=False)
# organizations.to_csv("baserow_exports/datarescue_organizations.csv", index=False)

In [8]:
# agencies = pd.DataFrame(get_results_json("https://baserow.datarescueproject.org/api/database/rows/table/645/?user_field_names=true"))[['Name']]
agencies.to_csv("../baserow_exports/datarescue_agencies.csv", index=False)

In [13]:
def create_agency_md(row):
    """
    This function creates a markdown file for each agency.
    """
    agency_path = "../_agencies"
    agency_filename = slugify(row['Name'])

    # Creating the agency markdown file
    agency_md = "---\n"
    agency_md += f"title: {clean_text(row['Name'])} \n"
    agency_md += "description: \n"
    agency_md += "---\n"

    # Writing the agency markdown file
    with open(f'{agency_path}/{agency_filename}.md', 'w') as output:
        output.write(agency_md)

In [14]:
agencies.apply(create_agency_md, axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
72    None
73    None
74    None
75    None
76    None
Length: 77, dtype: object

In [23]:
datasets = pd.read_csv("https://raw.githubusercontent.com/datarescueproject/portal/refs/heads/main/baserow_exports/datarescue_datasets.csv")

In [24]:
datasets

,dataset,notes,dataset_id,url,websites,organization,agency,categories,last_modified
0,Billion-Dollar Weather and Climate Disasters,NaN,1,https://www.ncei.noaa.gov/access/billions/mapping,ncei.noaa.gov,National Oceanic and Atmospheric Administration,Department of Commerce,[],2025-02-10
1,American Communities Survey (ACS),NaN,3,https://www.census.gov/programs-surveys/acs,census.gov,Census Bureau,Department of Commerce,[],2025-03-03
2,Enforcement and Compliance History Online (ECHO),NaN,13,https://echo.epa.gov/files/echodownloads,echo.epa.gov,Environmental Protection Agency,Environmental Protection Agency,[],2025-03-26
3,College Scorecard,NaN,15,https://collegescorecard.ed.gov/data/,collegescorecard.ed.gov,Office of Chief Information Officer,Department of Education,[],2025-02-11
4,Campus Safety and Security,NaN,16,https://ope.ed.gov/campussafety/#/datafile/list,ope.ed.gov,Office of Chief Information Officer,Department of Education,[],2025-02-11
...,...,...,...,...,...,...,...,...,...
2929,National Accounts (NIPA) Archive,NaN,5057,https://apps.bea.gov/histdata/histChildLevels....,bea.gov,Bureau of Economic Analysis,Department of Commerce,[],2026-02-22
2930,Fixed Asset Archive,NaN,5058,https://apps.bea.gov/histdata/histChildLevels....,bea.gov,Bureau of Economic Analysis,Department of Commerce,[],2026-02-22
2931,"National Center for HIV, Viral Hepatitis, STD,...",NaN,5059,https://gis.cdc.gov/grasp/nchhstpatlas/tables....,gis.cdc.gov,Centers for Disease Control and Prevention (CDC),Department of Health and Human Services,[],2026-02-26
2932,Fedscope Datasets from OPM,Diversity data removed from FedScope Data Cube...,5060,https://www.fedscope.opm.gov/,fedscope.opm.gov,Office of Personnel Management,Office of Personnel Management,[],2026-03-23
2933,Gross Domestic Product by Industry and Input-O...,NaN,5061,https://apps.bea.gov/histdatacore/histChildLev...,bea.gov,Bureau of Economic Analysis,Department of Commerce,[],2026-03-18

In [10]:
datasets = pd.read_csv("https://raw.githubusercontent.com/datarescueproject/portal/refs/heads/main/baserow_exports/datarescue_datasets.csv")
datasets.head()

,dataset,notes,dataset_id,url,websites,organization,agency,categories,last_modified,dataset_source_status
0,Billion-Dollar Weather and Climate Disasters,NaN,1,https://www.ncei.noaa.gov/access/billions/mapping,ncei.noaa.gov,National Oceanic and Atmospheric Administration,Department of Commerce,[],2025-02-10,NaN
1,American Communities Survey (ACS),NaN,3,https://www.census.gov/programs-surveys/acs,census.gov,Census Bureau,Department of Commerce,[],2025-03-03,NaN
2,Enforcement and Compliance History Online (ECHO),NaN,13,https://echo.epa.gov/files/echodownloads,echo.epa.gov,Environmental Protection Agency,Environmental Protection Agency,[],2025-03-26,NaN
3,College Scorecard,NaN,15,https://collegescorecard.ed.gov/data/,collegescorecard.ed.gov,Office of Chief Information Officer,Department of Education,[],2025-02-11,NaN
4,Campus Safety and Security,NaN,16,https://ope.ed.gov/campussafety/#/datafile/list,ope.ed.gov,Office of Chief Information Officer,Department of Education,[],2025-02-11,NaN

In [11]:
datasets.shape

(2934, 10)

In [12]:
import warnings
warnings.filterwarnings('ignore', category=requests.packages.urllib3.exceptions.InsecureRequestWarning)

In [14]:
ds_urls = datasets['url'].tolist()
url_statuses = []
url_status_notes = []
error_code_mapping = {    
    401: "Unauthorized: Authentication is required and has failed or has not yet been provided.",
    403: "Forbidden: Might be forbidden to access programmatically, but can be accessed via a browser.",
    404: "Not Found: The server can not find the requested resource.",
    500: "Internal Server Error: The server has encountered a situation it doesn't know how to handle.",
    502: "Bad Gateway: The server was acting as a gateway or proxy and received an invalid response from the upstream server.",
    503: "Service Unavailable: Unable to verify programatically, but might able to be accessed via a browser.",
}
for url in ds_urls:
    try:
        response = requests.head(url, allow_redirects=True, timeout=10, verify=False)
        if response.status_code == 200:
            # print(f"URL is valid: {url}")
            url_statuses.append(response.status_code)
            url_status_notes.append("Valid URL")
        else:
            print(f"URL returned status code {response.status_code}: {url}")
            url_statuses.append(response.status_code)
            url_status_notes.append(error_code_mapping[response.status_code] if response.status_code in error_code_mapping else "Other Error")
    except requests.exceptions.RequestException as e:
        print(f"Error accessing URL {url}: {e}")
        url_statuses.append(0)
        url_status_notes.append(f'error ({e})')

URL returned status code 404: https://www.fema.gov/about/openfema/data-sets/national-household-survey
URL returned status code 404: https://www.fema.gov/about/openfema/data-sets/grant-programs-directorate-preparedness-non-disasterassistance-firefighter-grants
URL returned status code 403: https://www.census.gov/naics/?input=1531&year=2022
Error accessing URL https://justice40tool.lbl.gov/: HTTPSConnectionPool(host='justice40tool.lbl.gov', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1628756d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
URL returned status code 403: https://www.phmsa.dot.gov/data-and-statistics/pipeline/gas-distribution-gas-gathering-gas-transmission-hazardous-liquids
URL returned status code 503: https://www.eia.gov/outlooks/aeo/data/browser/
URL returned status code 503: https://www.eia.gov/consumption/commercial/data/2018/
URL returned status code 503: https://www.eia.gov/electricity/data/eia860/
URL returned status code 503: https://www.eia.gov/electricity/data/eia861/
URL returned status code 503: https://www.eia.gov/electricity/data/eia923/
URL returned status code 404: https://www.cdc.gov/drugoverdose/rxrate-maps/opioid.html
URL returned status code 404: https://www.consumerfinance.gov/data-research/student-banking/deposit-product-marketing-agreements-and-data/
URL returned status code 404: https://www.samhsa.gov/data/data-we-collect/n-mhss
Error accessing URL https://www.imls.gov/research-evaluation/data-collection/state-library-administrative-agency-survey: HTTPConnectionPool(host='www.imls.gov', port=80): Max retries exceeded with url: /research-evaluation/surveys/state-library-administrative-agency-survey-slaa (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x165497580>, 'Connection to www.imls.gov timed out. (connect timeout=60)'))
URL returned status code 404: https://www.imls.gov/research-evaluation/data-collection/public-libraries-survey
Error accessing URL https://www.imls.gov/research-evaluation/data-collection/museum-data-files: HTTPConnectionPool(host='www.imls.gov', port=80): Max retries exceeded with url: /research-evaluation/data/museum-data-files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x16549e670>, 'Connection to www.imls.gov timed out. (connect timeout=60)'))
Error accessing URL https://www.imls.gov/research-evaluation/data-collection/public-needs-library-and-museum-services-survey: HTTPConnectionPool(host='www.imls.gov', port=80): Max retries exceeded with url: /research-evaluation/surveys/public-needs-for-library-and-museum-services-survey (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x1654a12b0>, 'Connection to www.imls.gov timed out. (connect timeout=60)'))
Error accessing URL https://www.imls.gov/data/surveys-data/heritage-health-information-survey-hhis: HTTPConnectionPool(host='www.imls.gov', port=80): Max retries exceeded with url: /research-evaluation/surveys/heritage-health-info-survey (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x1654a1eb0>, 'Connection to www.imls.gov timed out. (connect timeout=60)'))
Error accessing URL https://www.imls.gov/research-tools/data-collection/social-wellbeing-report: HTTPConnectionPool(host='www.imls.gov', port=80): Max retries exceeded with url: /research-evaluation/data/social-wellbeing-report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x1654a16d0>, 'Connection to www.imls.gov timed out. (connect timeout=60)'))
Error accessing URL https://www.imls.gov/data/data-catalog/imls-indicators-workbook-economic-status-and-broadband-availability-and-adoption: HTTPConnectionPool(host='www.imls.gov', port=80): Max retries exceeded with url: /research-evaluation/data/imls-indicators-workbook-economic-status-and-broadband-availability-and-adoption (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x16549eac0>, 'Connection to www.imls.gov timed out. (connect timeout=60)'))
URL returned status code 404: https://archives.huduser.gov/portal/datasets/hads.html
URL returned status code 404: https://www.huduser.gov/portal/datasets/hds_disability.html
URL returned status code 404: https://www.huduser.gov/portal/datasets/hsg_discrimination.html
URL returned status code 404: https://www.energy.gov/justice/energy-justice-dashboard-beta
URL returned status code 403: https://www.hrsa.gov/grants/find-funding/HRSA-23-056
URL returned status code 403: https://www.bls.gov/tus/
URL returned status code 403: https://bphc.hrsa.gov/data-reporting/health-center-patient-survey
URL returned status code 403: https://www.bls.gov/
URL returned status code 403: https://www.bls.gov/
URL returned status code 403: https://www.bls.gov/
URL returned status code 403: https://mchb.hrsa.gov/data-research/national-survey-childrens-health
URL returned status code 403: https://www.hhs.gov/
URL returned status code 403: https://www.noaa.gov/
URL returned status code 503: https://www.eia.gov/consumption/manufacturing/data/2018/#r13
URL returned status code 503: https://www.eia.gov/naturalgas/ngqs/#?report=RP9&year1=2017&year2=2017&company=Name
URL returned status code 503: https://www.eia.gov/consumption/residential/data/2020/
URL returned status code 404: https://sab.epa.gov/ords/sab/f?p=100:18:16490947993:::18:P18_ID:2601
URL returned status code 404: https://www.epa.gov/climate-indicators
Error accessing URL https://ghgdata.epa.gov/ghgp/main.do#/facility/: HTTPConnectionPool(host='ghgdata.epa.gov', port=80): Max retries exceeded with url: /flight/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x16548f220>, 'Connection to ghgdata.epa.gov timed out. (connect timeout=60)'))
URL returned status code 403: https://www.noaa.gov/bil-ira-awards-explorer
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/borehole: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/climate-forcing: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/coral-sclerosponge: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/fauna: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/fire-history: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/historical: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/ice-core: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/insect: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/lake: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/lake-level-reconstruction: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/loess-paleosols: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/paleoceanography: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/modeling: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/plant-macrofossil: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/pollen: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error accessing URL https://www.ncei.noaa.gov/products/paleoclimatology/speleothem: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
URL returned status code 404: https://www.nrel.gov/analysis/electrification-futures.html
URL returned status code 404: https://github.com/NREL-Sienna-Sienna
Error accessing URL https://www.fpds.gov/fpdsng_cms/index.php/en/: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
URL returned status code 404: https://www.hudexchange.info/manage-a-program/census/low-mod-income-summary-data/
URL returned status code 404: https://www.hudexchange.info/resource/4832/2015-ahar-part-1-pit-estimates-of-homelessness/
Error accessing URL https://tools.niehs.nih.gov/cchhl/index.cfm: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
URL returned status code 202: https://www.ahrq.gov/sdoh/data-analytics.html
URL returned status code 202: https://www.ahrq.gov/sdoh/data-analytics/sdoh-beta-database.html
URL returned status code 404: https://www.census.gov/programs-surveys/community-resilience-estimates/data/supplement.html
URL returned status code 403: https://www.fmcs.gov/resources/documents-and-data/
URL returned status code 403: https://www.fmcs.gov/resources/documents-and-data/
URL returned status code 403: https://www.mbda.gov/research/data/mbda-grantees
URL returned status code 403: https://www.mbda.gov/research/data/Firm%20Statistics%20by%20Demographics%20%282020%29
URL returned status code 403: https://www.mbda.gov/research/data/Firm%20Statistics%20by%20Demographics%20%282021%29
URL returned status code 503: https://www.ncei.noaa.gov/data/oceans/ndbc/cmanwx/
URL returned status code 404: https://www.cdc.gov/maternal-mortality/php/pregnancy-mortality-surveillance/index.html
URL returned status code 404: https://www.cdc.gov/nchs/pressroom/sosmap/firearm_mortality/firearm.htm
URL returned status code 403: https://mchb.hrsa.gov/data-research/chartbooks
URL returned status code 403: https://mchb.hrsa.gov/data-research/national-survey-childrens-health
URL returned status code 403: https://bloodstemcell.hrsa.gov/data/donation-and-transplantation-statistics/donor-registry-data
URL returned status code 403: https://bloodstemcell.hrsa.gov/data/donation-and-transplantation-statistics/transplant-activity-report#data
URL returned status code 403: https://www.transit.dot.gov/ntd/monthly-ridership
URL returned status code 403: https://www.bts.gov/content/us-hazardous-materials-shipments-transportation-mode-2007
URL returned status code 404: https://efile.fara.gov/ords/fara/f?p=1381:1:7299515917868:::::
URL returned status code 403: https://voices.nmfs.noaa.gov/
URL returned status code 404: https://www.ncei.noaa.gov/data/oceans/ndbc/hfradar/rtv/
URL returned status code 403: https://patentsview.org/download/data-download-tables
URL returned status code 503: https://www.eia.gov/electricity/data/state/
URL returned status code 403: https://www.bts.gov/ctp
Error accessing URL https://www.ncei.noaa.gov/products/natural-hazards: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
URL returned status code 404: https://data.bts.gov/dataset/Bikeshare/mqfn-syak/about_data
URL returned status code 403: https://www.ngdc.noaa.gov/mgg/shorelines/gshhs.html
URL returned status code 403: https://www.ncei.noaa.gov/products/geological-history-world-ocean-crust
URL returned status code 404: https://www.ncei.noaa.gov/data/sumd
URL returned status code 403: https://www.nhtsa.gov/file-downloads?p=nhtsa/downloads/CRSS/
URL returned status code 403: https://www.ngdc.noaa.gov/mgg/bathymetry/apb/data/
Error accessing URL https://www.ncei.noaa.gov/products/estuarine-bathymetric-digital-elevation-models: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
URL returned status code 404: https://www.webapps.nwfsc.noaa.gov/data/metadata/observer.gemm_fact
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:6769c4a7d34e8399fbb80311
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:ASC55
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:662fb3e5d34ea70bd5f26088
URL returned status code 404: https://www.ncei.noaa.gov/maps/sample_index/
URL returned status code 403: https://www.nhtsa.gov/nhtsa-datasets-and-apis
URL returned status code 403: https://www.bls.gov/emp/data.htm
URL returned status code 403: https://www.bls.gov/jlt/data.htm
URL returned status code 503: https://www.eia.gov/opendata/
URL returned status code 404: https://www.cdc.gov/bird-flu/situation-summary/data-map-commercial.html
URL returned status code 404: https://www.hud.gov/AFFH
Error accessing URL https://www.regstats.usda.gov/: HTTPSConnectionPool(host='www.usda.gov', port=443): Read timed out. (read timeout=60)
URL returned status code 404: https://www.epa.gov/ejscreen
Error accessing URL https://www.usda.gov/about-usda/general-information/priorities/equity-usda/equity-commission: HTTPSConnectionPool(host='www.usda.gov', port=443): Read timed out. (read timeout=60)
URL returned status code 403: https://home.treasury.gov/about/offices/equity-hub/TACRE/tacre-meeting-materials
URL returned status code 403: https://www.nhtsa.gov/nhtsa-datasets-and-apis
URL returned status code 403: https://www.cpsc.gov/Research--Statistics/NEISS-Injury-Data
URL returned status code 403: https://www.cpsc.gov/Research--Statistics/NEISS-Injury-Data
URL returned status code 503: https://www.eia.gov/
URL returned status code 202: https://www.ahrq.gov/research/findings/nhqrdr/index.html
URL returned status code 403: https://apps.cr.nps.gov/nagprapublic/Home/Inventory
URL returned status code 404: https://www.ncei.noaa.gov/data/oceans/ndbc/hfradar/radial/
Error accessing URL https://www.ncei.noaa.gov/maps/coastal-ecosystems/viewer.htm: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:ASC136
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:62f54e84d34eacf53973a9de
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:65eb3b41d34e14033297dbe2
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:61784165d34e4c6b7fe2a4df
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:626830b2d34e76103ccfd4f1
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:65775d6ad34e952b22746199
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:6171a037d34ea36449a7c876
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:5e95d84482ce172707f252ef
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:ASC177
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:62e2c58cd34e394b65364ed5
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:61d87383d34ed79294009f30
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:62e2c72fd34e394b65364ee4
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:665de174d34e19fd55a96bf6
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:667058f6d34e2fc9b7e49c18
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:66d72535d34eef5af66ca5ff
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:6388d806d34ed907bf78e862
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:6419f727d34eb496d1d2a0e1
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:64d12592d34ef477cf3bfd29
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:66ffdc54d34e80be174ae7d1
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:6228e7f1d34ee0c6b38b884d
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:ASC210
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:6633ce58d34ea70bd5f290e1
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:6262f2b0d34e85fa62bb60bc
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:64ac0e71d34e70357a28aeb6
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:6685a517d34e8a8b016cdb17
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:6446cc2fd34ee8d4adec6c45
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:ASC246
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:6387a18ad34ed907bf784db7
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:65400e6dd34ee4b6e05bc9ba
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:ASC402
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:5fd10f1dd34e30b91239b703
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:ASC277
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:ASC570
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:59de57ece4b05fe04ccd3997
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:581a3974e4b0bb36a4ca2f55
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:ASC53
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:5d697cc3e4b0c4f70cf294de
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:662fc51ad34ea70bd5f2625d
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:ASC214
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:ASC199
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:65e25103d34e5855ff4cfb45
URL returned status code 404: https://data.usgs.gov/datacatalog/data/USGS:66d9ed16d34eef5af66d534b
URL returned status code 403: https://www.bts.gov/faf
URL returned status code 403: https://www.saferproducts.gov/PublicSearch
URL returned status code 403: https://www.cpsc.gov/Recalls/violations
Error accessing URL https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
URL returned status code 403: https://www.bts.gov/browse-statistical-products-and-data/info-gallery/average-daily-number-people-screened-tsa-0
URL returned status code 403: https://www.cpsc.gov/Data/Monthly-Progress-Reports
Error accessing URL nan: Invalid URL 'nan': No scheme supplied. Perhaps you meant https://nan?
URL returned status code 403: https://www.bls.gov/oes/data.htm
URL returned status code 403: https://www.bls.gov/eci/data.htm
URL returned status code 503: https://www.eia.gov/state/seds/seds-data-fuel.php?sid=US#DataFiles
URL returned status code 503: https://www.eia.gov/electricity/state/
URL returned status code 500: https://maps2.dcgis.dc.gov/dcgis/rest/services/FEEDS/MPD/FeatureServer/9
Error accessing URL data.usaid.gov: Invalid URL 'data.usaid.gov': No scheme supplied. Perhaps you meant https://data.usaid.gov?
Error accessing URL data.usaid.gov: Invalid URL 'data.usaid.gov': No scheme supplied. Perhaps you meant https://data.usaid.gov?

In [15]:
datasets['url_status'] = url_statuses
datasets['url_status_notes'] = url_status_notes
datasets.to_csv("../baserow_exports/dataset_urlcheck_status.csv", index=False)

In [1]:
import json
import pandas as pd
import requests

In [ ]:
try:
    resp = requests.get(url="https://findgovdata.org/files/last_seen.json")

{'generated': '2026-07-09T08:17:04.597961Z',
 'filter': 'last_seen < "2026-07-09"',
 'documents_count': 2279,
 'documents': [{'id': 'ba1f2b82-6222-5a74-9255-862e2ca6fac7',
   'timestamp': '2022-02-22T00:00:00Z',
   'tags': None,
   'name': 'Commercial Harvest Sites',
   'description': 'Locations of commercial shellfish harvest sites (shellfish harvesters, shellstock shippers, and shucker packers) in Washington State. Also displayed on the Commercial Shellfish Map Viewer here: https://fortress.wa.gov/doh/oswpviewer/index.html Relay and wet storage sites are not included.',
   'content': None,
   'metadata': {'organization': {'organization_type': 'State Government',
     'logo': 'https://raw.githubusercontent.com/GSA/logo/refs/heads/master/wa-opendata.png',
     'name': 'State of Washington',
     'slug': 'washington',
     'description': None,
     'aliases': ['wa'],
     'id': 'bccbad82-abc4-4712-bd29-3e194e7a8042'},
    'imported': '2026-05-30T14:47:38.827030Z',
    'organization_type': 'State Government',
    'dcat': {'identifier': 'https://www.arcgis.com/home/item.html?id=b625d6bce5864180bcc7d4e59a03a000&sublayer=0',
     '@type': 'dcat:Dataset',
     'modified': '2022-02-22',
     'contactPoint': {'hasEmail': 'mailto:no-reply@data.wa.gov',
      'fn': 'WADOHAdmin',
      '@type': 'vcard:Contact'},
     'landingPage': 'https://geo.wa.gov/datasets/WADOH::commercial-harvest-sites',
     'spatial': '-124.2256,46.3941,-122.2981,48.9936',
     'distribution': [{'mediaType': 'text/csv',
       'title': 'CSV',
       'downloadURL': 'https://geo.wa.gov/api/download/v1/items/b625d6bce5864180bcc7d4e59a03a000/csv?layers=0',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/vnd.ms-excel',
       'title': 'Excel',
       'downloadURL': 'https://geo.wa.gov/api/download/v1/items/b625d6bce5864180bcc7d4e59a03a000/excel?layers=0',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'text/plain',
       'title': 'Feature Collection',
       'downloadURL': 'https://geo.wa.gov/api/download/v1/items/b625d6bce5864180bcc7d4e59a03a000/featureCollection?layers=0',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/zip',
       'title': 'File Geodatabase',
       'downloadURL': 'https://geo.wa.gov/api/download/v1/items/b625d6bce5864180bcc7d4e59a03a000/filegdb?layers=0',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/geopackage+sqlite3',
       'title': 'GeoPackage',
       'downloadURL': 'https://geo.wa.gov/api/download/v1/items/b625d6bce5864180bcc7d4e59a03a000/geoPackage?layers=0',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/vnd.geo+json',
       'title': 'GeoJSON',
       'downloadURL': 'https://geo.wa.gov/api/download/v1/items/b625d6bce5864180bcc7d4e59a03a000/geojson?layers=0',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/vnd.google-earth.kml+xml',
       'title': 'KML',
       'downloadURL': 'https://geo.wa.gov/api/download/v1/items/b625d6bce5864180bcc7d4e59a03a000/kml?layers=0',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/zip',
       'title': 'Shapefile',
       'downloadURL': 'https://geo.wa.gov/api/download/v1/items/b625d6bce5864180bcc7d4e59a03a000/shapefile?layers=0',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/geopackage+sqlite3',
       'title': 'SQLite Geodatabase',
       'downloadURL': 'https://geo.wa.gov/api/download/v1/items/b625d6bce5864180bcc7d4e59a03a000/sqlite?layers=0',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'text/html',
       'title': 'ArcGIS Hub Dataset',
       'downloadURL': 'https://geo.wa.gov/datasets/WADOH::commercial-harvest-sites',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/json',
       'title': 'ArcGIS GeoService',
       'downloadURL': 'https://services8.arcgis.com/rGGrs6HCnw87OFOT/arcgis/rest/services/Commercial_Harvest_Sites/FeatureServer/0',
       '@type': 'dcat:Distribution'}],
     'issued': '2021-03-24',
     'title': 'Commercial Harvest Sites',
     'theme': ['geospatial'],
     'publisher': {'name': 'Washington State Department of Health',
      '@type': 'org:Organization'},
     'accessLevel': 'public'},
    'year_updated': 2022,
    'slug': 'commercial-harvest-sites',
    'organization_name': 'State of Washington',
    'publisher': 'Washington State Department of Health',
    'distribution_count': 11,
    'last_seen': '2026-06-15T02:22:37.381247Z'},
   'custom_vectors': None},
  {'id': '4dfe14a1-2d99-5d29-99b7-0e04d4cec968',
   'timestamp': '2023-09-11T20:44:21Z',
   'tags': None,
   'name': 'Heather Vole Predicted Habitat - CWHR M130 [ds2584]',
   'description': 'The datasets used in the creation of the predicted Habitat Suitability models includes the CWHR range maps of Californias regularly-occurring vertebrates which were digitized as GIS layers to support the predictions of the CWHR System software. These vector datasets of CWHR range maps are one component of California Wildlife Habitat Relationships (CWHR), a comprehensive information system and predictive model for Californias wildlife. The CWHR System was developed to support habitat conservation and management, land use planning, impact assessment, education, and research involving terrestrial vertebrates in California. CWHR contains information on life history, management status, geographic distribution, and habitat relationships for wildlife species known to occur regularly in California. Range maps represent the maximum, current geographic extent of each species within California. They were originally delineated at a scale of 1:5,000,000 by species-level experts and have gradually been revised at a scale of 1:1,000,000. For more information about CWHR, visit the CWHR webpage (https://www.wildlife.ca.gov/Data/CWHR). The webpage provides links to download CWHR data and user documents such as a look up table of available range maps including species code, species name, and range map revision history; a full set of CWHR GIS data; .pdf files of each range map or species life history accounts; and a User Guide.The models also used the CALFIRE-FRAP compiled "best available" land cover data known as Fveg. This compilation dataset was created as a single data layer, to support the various analyses required for the Forest and Rangeland Assessment, a legislatively mandated function. These data are being updated to support on-going analyses and to prepare for the next FRAP assessment in 2015. An accurate depiction of the spatial distribution of habitat types within California is required for a variety of legislatively-mandated government functions. The California Department of Forestry and Fire Protections CALFIRE Fire and Resource Assessment Program (FRAP), in cooperation with California Department of Fish and Wildlife VegCamp program and extensive use of USDA Forest Service Region 5 Remote Sensing Laboratory (RSL) data, has compiled the "best available" land cover data available for California into a single comprehensive statewide data set. The data span a period from approximately 1990 to 2014. Typically the most current, detailed and consistent data were collected for various regions of the state. Decision rules were developed that controlled which layers were given priority in areas of overlap. Cross-walks were used to compile the various sources into the common classification scheme, the California Wildlife Habitat Relationships (CWHR) system.CWHR range data was used together with the FVEG vegetation maps and CWHR habitat suitability ranks to create Predicted Habitat Suitability maps for species. The Predicted Habitat Suitability maps show the me...',
   'content': None,
   'metadata': {'imported': '2026-05-30T14:47:38.827030Z',
    'organization': {'organization_type': 'State Government',
     'logo': 'https://raw.githubusercontent.com/GSA/logo/refs/heads/master/state_CA.png',
     'name': 'State of California',
     'slug': 'california',
     'description': None,
     'aliases': ['ca'],
     'id': 'ae56c24b-46d3-4688-965e-94bdc208164f'},
    'dcat': {'identifier': '552e5341-70b7-425a-8032-1ff3ee4251d1',
     '@type': 'dcat:Dataset',
     'modified': '2023-09-11T20:44:21.000Z',
     'contactPoint': {'hasEmail': 'mailto:geodata@wildlife.ca.gov',
      'fn': 'BIOS_Admin',
      '@type': 'vcard:Contact'},
     'accessLevel': 'public',
     'title': 'Heather Vole Predicted Habitat - CWHR M130 [ds2584]',
     'distribution': [{'accessURL': 'http://withheld',
       'title': 'Heather Vole Predicted Habitat - CWHR M130 [ds2584]',
       '@type': 'dcat:Distribution'},
      {'accessURL': 'https://data-cdfw.opendata.arcgis.com/content/CDFW::heather-vole-predicted-habitat-cwhr-m130-ds2584',
       'format': 'HTML',
       'title': 'ArcGIS Hub Dataset',
       '@type': 'dcat:Distribution'},
      {'accessURL': 'https://www.wildlife.ca.gov/Data/BIOS',
       'title': 'Heather Vole Predicted Habitat - CWHR M130 [ds2584]',
       '@type': 'dcat:Distribution'},
      {'accessURL': 'https://www.wildlife.ca.gov/Data/CWHR',
       'title': 'Heather Vole Predicted Habitat - CWHR M130 [ds2584]',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/octet-stream',
       'title': 'ArcGIS GeoService',
       'format': 'ArcGIS GeoServices REST API',
       'downloadURL': 'https://tiledimageservices2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2584_cru/ImageServer',
       '@type': 'dcat:Distribution'}],
     'issued': '2023-08-14T21:42:57.000Z',
     'theme': ['Natural Resources'],
     'publisher': {'name': 'California Department of Fish and Wildlife',
      '@type': 'org:Organization'},
     'license': 'http://www.opendefinition.org/licenses/cc-by'},
    'organization_type': 'State Government',
    'year_updated': 2023,
    'slug': 'heather-vole-predicted-habitat-cwhr-m130-ds2584',
    'organization_name': 'State of California',
    'publisher': 'California Department of Fish and Wildlife',
    'distribution_count': 5,
    'last_seen': '2026-06-26T07:46:54.084098Z'},
   'custom_vectors': None},
  {'id': '40bc5a27-f359-5015-be1f-03342869ed58',
   'timestamp': '2026-02-16T00:00:00Z',
   'tags': None,
   'name': 'Iowa UI Average Benefit Cost Rate and Average Tax Rate Based on Total Wages',
   'description': 'This dataset computes the Benefit Cost Rate and Average Tax Rate based on total wages. UI benefits and contributions are divided by total wages in order to control for employment and wage growth. The highest Benefit Cost Rate was 2.63% in 1982. The highest Average Tax Rate based on total wages was 1.89% in 1985. The lowest Benefit Cost Rate was 0.35% in 2023. The lowest Average Tax Rate based on total wages was 0.49% in 1988. Data excludes reimbursable employers. (Time period: 1980-2025).',
   'content': None,
   'metadata': {'imported': '2026-05-30T14:47:38.827030Z',
    'organization': {'organization_type': 'State Government',
     'logo': 'https://raw.githubusercontent.com/GSA/logo/refs/heads/master/state_IA.png',
     'name': 'State of Iowa',
     'slug': 'iowa',
     'description': None,
     'aliases': ['ia'],
     'id': '2efac508-2a39-46d4-8d0c-e034d17e928f'},
    'dcat': {'identifier': 'https://data.iowa.gov/api/views/a6wr-r836',
     'accessLevel': 'public',
     'title': 'Iowa UI Average Benefit Cost Rate and Average Tax Rate Based on Total Wages',
     'contactPoint': {'hasEmail': 'mailto:no-reply@data.iowa.gov',
      'fn': 'Iowa Unemployment Insurance Statistics',
      '@type': 'vcard:Contact'},
     'landingPage': 'https://data.iowa.gov/d/a6wr-r836',
     'modified': '2026-02-16',
     'distribution': [{'mediaType': 'application/json',
       'describedByType': 'application/json',
       'describedBy': 'https://data.iowa.gov/api/views/a6wr-r836/columns.json',
       'downloadURL': 'https://data.iowa.gov/api/views/a6wr-r836/rows.json?accessType=DOWNLOAD',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/rdf+xml',
       'describedByType': 'application/rdf+xml',
       'describedBy': 'https://data.iowa.gov/api/views/a6wr-r836/columns.rdf',
       'downloadURL': 'https://data.iowa.gov/api/views/a6wr-r836/rows.rdf?accessType=DOWNLOAD',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/xml',
       'describedByType': 'application/xml',
       'describedBy': 'https://data.iowa.gov/api/views/a6wr-r836/columns.xml',
       'downloadURL': 'https://data.iowa.gov/api/views/a6wr-r836/rows.xml?accessType=DOWNLOAD',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'text/csv',
       'downloadURL': 'https://data.iowa.gov/api/views/a6wr-r836/rows.csv?accessType=DOWNLOAD',
       '@type': 'dcat:Distribution'}],
     'issued': '2019-09-06',
     '@type': 'dcat:Dataset',
     'theme': ['Workforce'],
     'publisher': {'name': 'data.iowa.gov', '@type': 'org:Organization'},
     'license': 'https://www.usa.gov/government-works'},
    'organization_type': 'State Government',
    'year_updated': 2026,
    'slug': 'iowa-ui-average-benefit-cost-rate-and-average-tax-rate-based-on-total-wages',
    'organization_name': 'State of Iowa',
    'publisher': 'data.iowa.gov',
    'distribution_count': 4,
    'last_seen': '2026-06-04T01:22:27.684786Z'},
   'custom_vectors': None},
  {'id': '0ed33da8-5cef-57ed-b790-3fd19b63f19b',
   'timestamp': '2026-06-08T00:00:00Z',
   'tags': None,
   'name': 'OrbView-2 SeaWiFS Level-3 Global Mapped Inherent Optical Properties (IOP) Data, version 2022.0',
   'description': 'The Inherent Optical Properties (IOP) suite provides per-pixel inherent optical properties - quantities that describe how seawater and its constituents absorb and scatter light, independent of illumination or viewing geometry. IOPs are retrieved from spectral Remote Sensing Reflectance (Rrs) using the default configuration of the Generalized Inherent Optical Properties (GIOP) model framework. These products support water-type classification, water-clarity assessment, biogeochemical studies, and forward/adjoint radiative-transfer applications, and they enable more robust cross-sensor comparisons than purely apparent (AOP) products. Geophysical variables in this suite include: - a — Total absorption coefficient (sum of pure water + phytoplankton + CDOM/detritus, m⁻¹) - bb — Total backscattering coefficient (m⁻¹) - aph_443 — Phytoplankton absorption coefficient at 443 nm (m⁻¹) - aph_unc_443 — Uncertainty in absorption due to phytoplankton at 443 nm (m⁻¹) - adg_443 — Combined CDOM + non-algal detritus absorption coefficient at 443nm; accompanied by adg_s (spectral slope, units nm⁻¹). - adg_unc_443 — Uncertainty in absorption due to gelbstoff and detrital material at 443 nm (m⁻¹). - bbp_443 — Particulate backscattering coefficient at 443nm (m⁻¹); include bbp_s (power-law slope, unitless) describing spectral shape. - bbp_unc_443 — Uncertainty in particulate backscattering at 443 nm (m⁻¹). - rrsdiff — Fractional mean Rrs difference.',
   'content': None,
   'metadata': {'imported': '2026-06-10T21:20:52.902391Z',
    'organization': {'organization_type': 'Federal Government',
     'logo': 'https://raw.githubusercontent.com/GSA/logo/refs/heads/master/nasa.png',
     'name': 'National Aeronautics and Space Administration',
     'slug': 'nasa',
     'description': None,
     'aliases': [''],
     'id': 'f4ca4614-8901-409b-8553-2e994ad10023'},
    'dcat': {'identifier': '10.5067/ORBVIEW-2/SeaWiFS/L3M/IOP/2022.0',
     'license': 'https://www.usa.gov/government-works',
     'modified': '2026-06-08',
     'contactPoint': {'hasEmail': 'mailto:earthdata-support@nasa.gov',
      'fn': 'Earthdata Forum',
      '@type': 'vcard:Contact'},
     'programCode': ['026:000'],
     'spatial': '["CARTESIAN", [{"SouthBoundingCoordinate": -90, "EastBoundingCoordinate": 180, "NorthBoundingCoordinate": 90, "WestBoundingCoordinate": -180}]]',
     'distribution': [{'conformsTo': 'http://www.isotc211.org/2005/gmi',
       'mediaType': 'text/xml',
       'title': 'Original Metadata',
       'format': 'ISO',
       'description': "The metadata's original source.",
       'downloadURL': 'https://cmr.earthdata.nasa.gov/search/concepts/C3113254783-OB_CLOUD.iso19115',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/octet-stream',
       'format': 'BIN',
       'downloadURL': 'https://nasa.github.io/oceandata-notebooks/',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/octet-stream',
       'format': 'BIN',
       'downloadURL': 'https://oceancolor.gsfc.nasa.gov/data/reprocessing/',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/pdf',
       'format': 'PDF',
       'downloadURL': 'https://oceancolor.gsfc.nasa.gov/files/atbd/atbd-obdaac-inherent-optical-properties.pdf',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/pdf',
       'format': 'PDF',
       'downloadURL': 'https://oceancolor.gsfc.nasa.gov/files/obdaac-ancillary-data-sources.pdf',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/pdf',
       'format': 'PDF',
       'downloadURL': 'https://oceancolor.gsfc.nasa.gov/files/seawifs-modified-near-infrared-correction-algorithm.pdf',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/octet-stream',
       'format': 'BIN',
       'downloadURL': 'https://oceandata.sci.gsfc.nasa.gov/directdataaccess/Level-3%20Mapped/SeaWiFS/',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/octet-stream',
       'format': 'BIN',
       'downloadURL': 'https://oceandata.sci.gsfc.nasa.gov/opendap/SeaWiFS/L3SMI/',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/octet-stream',
       'format': 'BIN',
       'downloadURL': 'https://search.earthdata.nasa.gov/search?q=%2522SeaWiFS_L3m_IOP%2522',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/octet-stream',
       'format': 'BIN',
       'downloadURL': 'https://www.earthdata.nasa.gov/data/instruments/SeaWiFS',
       '@type': 'dcat:Distribution'},
      {'mediaType': 'application/octet-stream',
       'format': 'BIN',
       'downloadURL': 'https://www.earthdata.nasa.gov/data/platforms/space-based-platforms/OrbView-2',
       '@type': 'dcat:Distribution'}],
     '@type': 'dcat:Dataset',
     'publisher': {'name': 'NASA/GSFC/SED/ESD/GCDC/OB.DAAC;OBPG',
      '@type': 'org:Organization'},
     'title': 'OrbView-2 SeaWiFS Level-3 Global Mapped Inherent Optical Properties (IOP) Data, version 2022.0',
     'theme': ['Earth Science'],
     'temporal': '1997-09-04/2010-12-11',
     'bureauCode': ['026:00'],
     'accessLevel': 'public'},
    'organization_type': 'Federal Government',
    'year_updated': 2026,
    'slug': 'orbview-2-seawifs-level-3-global-mapped-inherent-optical-properties-iop-data-version-2022-',
    'organization_name': 'National Aeronautics and Space Administration',
    'distribution_count': 11,
    'publisher': 'NASA/GSFC/SED/ESD/GCDC/OB.DAAC;OBPG',
    'last_seen': '2026-06-15T02:21:27.298564Z'},
   'custom_vectors': None},
  {'id': 'a763447a-87b1-5f91-be02-1d5df52aa123',
   'timestamp': '2026-06-08T00:00:00Z',
   'tags': None,
   'name': 'Sentinel-3B OLCI Level-3 Global Mapped Earth-observation Reduced Resolution (ERR) Diffuse Attenuation Coefficient of Downwelling Irradiance (KD) Data, version 2022.0',

In [127]:
def get_URLs_from_dist(arr):
    urls = []
    if arr:
        for a in arr:
            try: 
                urls.append(a['accessURL'])
            except:
                pass
            try: 
                urls.append(a['downloadURL'])
            except:
                pass
    
    urls = list(set(urls))
    if len(urls) > 0:
        url_out = ", ".join(urls)
    else:
        url_out = ""
    return url_out


data_gov_missing = pd.DataFrame(resp.json()['documents'])
metadata = pd.json_normalize(data_gov_missing['metadata'])
df_expanded = data_gov_missing.drop(columns=['metadata']).join(metadata)
df_expanded = df_expanded[['id', 'name', 'description',
'organization_type', 'organization_name', 'publisher', 
'last_seen', 'dcat.landingPage','distribution_count',
'dcat.distribution']]

df_expanded['dcat.distribution'] = df_expanded['dcat.distribution'].fillna("")
df_expanded['dcat.landingPage'] = df_expanded['dcat.landingPage'].fillna("")
df_expanded['download_urls'] = df_expanded['dcat.distribution'].apply(get_URLs_from_dist)

df_expanded['last_seen'] = pd.to_datetime(df_expanded['last_seen'], format='ISO8601')
df_expanded['last_seen'] = df_expanded['last_seen'].dt.date

df_expanded = df_expanded.drop(columns=['dcat.distribution','distribution_count']).rename(columns={'dcat.landingPage':'source_url','id':'hashed_id'})

In [ ]:
df_expanded.last_seen = df_expanded.last_seen.astype('str')

In [ ]:
for r in df_expanded_json:
    requests.post(
    "https://baserow.datarescueproject.org/api/database/rows/table/1054/?user_field_names=true",
    headers={
        "Authorization": f"Token {BASEROW_ACCESS_TOKEN}",
        "Content-Type": "application/json"
    },
    json=r
    )

KeyboardInterrupt:

In [7]:
def get_results_json(url, api_key=BASEROW_ACCESS_TOKEN):
    table = requests.get(
        url,
        headers={
            "Authorization": f"Token {api_key}"
        }
    )

    res = table.json()['results']
    if table.json()['next'] is not None:
        res.extend(get_results_json(table.json()['next']))

    return res

In [ ]:
rows_on_baserow = get_results_json("https://baserow.datarescueproject.org/api/database/rows/table/1054/?user_field_names=true")
rows_on_baserow = pd.DataFrame(rows_on_baserow)
rows_on_baserow = rows_on_baserow.drop(columns=['order'])
rows_to_add = df_expanded[~df_expanded.hashed_id.isin(rows_on_baserow.hashed_id)]
rows_to_add_json = rows_to_add.to_dict(orient='records')

In [ ]:
requests.post(
    "https://baserow.datarescueproject.org/api/database/rows/table/1054/?user_field_names=true",
    headers={
        "Authorization": f"Token {BASEROW_ACCESS_TOKEN}",
        "Content-Type": "application/json"
    },
    json=rows_to_add_json[0]
    )

In [187]:
rows_to_toggle_status = rows_on_baserow[~rows_on_baserow.hashed_id.isin(df_expanded.hashed_id)]

In [197]:
len(rows_to_toggle_status)

0

In [ ]:
for i in rows_to_toggle_status.id:
    requests.patch(
        "https://baserow.datarescueproject.org/api/database/rows/table/1054/{i}/?user_field_names=true",
        headers={
            "Authorization": f"Token {BASEROW_ACCESS_TOKEN}",
            "Content-Type": "application/json"
        },
        json={
            "status":"Returned to data.gov"
            "last_seen": str(dt.date.today())
        }
    )

In [202]:
requests.get("https://data.iowa.gov/d/4y7u-nzj9")

In [ ]:
tracker_table_ids = [640, 901]
volunteer_table_ids = [1125, 1124]
Vol_API = ""
BASEROW_ACCESS_TOKEN = ""

In [185]:
def extract_link_values(value):
    if isinstance(value, dict):
        return value.get("value", value)

    if isinstance(value, list):
        return [
            item.get("value", item) if isinstance(item, dict) else item
            for item in value
        ]
        
    return value

def replace_linked_records_with_values(rows):
    """
    Convert:
        [{"id": 12, "value": "Alice"}]
    into:
        ["Alice"]
    """
    converted_rows = []
    fields = rows[0].keys()
    for row in rows:
        converted_row = row.copy()

        for field in fields:
            converted_row[field] = extract_link_values(converted_row.get(field))

        converted_rows.append(converted_row)

    return converted_rows

import numpy as np

def arrays_to_strings(df):
    converted = df.copy()

    def convert(value):
        if isinstance(value, (list, tuple, np.ndarray)):
            return ",".join(
                str(item.get("value", item))
                if isinstance(item, dict)
                else str(item)
                for item in value
            )
        return value

    for column in converted.columns:
        converted[column] = converted[column].map(convert)

    return converted

In [191]:
rows_on_tracker = get_results_json("https://baserow.datarescueproject.org/api/database/rows/table/640/?user_field_names=true",BASEROW_ACCESS_TOKEN)
rows_on_volunteer = get_results_json("https://baserow.datarescueproject.org/api/database/rows/table/1125/?user_field_names=true",Vol_API)

rows_on_tracker = replace_linked_records_with_values(rows_on_tracker)
rows_on_tracker = pd.DataFrame(rows_on_tracker)
rows_on_tracker = rows_on_tracker.drop(columns=['order'])
rows_on_tracker = arrays_to_strings(rows_on_tracker)
if rows_on_volunteer:
    rows_on_volunteer = replace_linked_records_with_values(rows_on_volunteer)
    rows_on_volunteer = pd.DataFrame(rows_on_volunteer)
    rows_on_volunteer = rows_on_volunteer.drop(columns=['order'])
    rows_on_volunteer = arrays_to_strings(rows_on_volunteer)
else:
    rows_on_volunteer = rows_on_tracker.iloc[0:0].copy()

In [ ]:
cols = list(set(rows_on_tracker.columns).intersection(rows_on_volunteer.columns))
cols = [c for c in cols if c!='id']
merged = rows_on_tracker.merge(rows_on_volunteer,on=cols,how="outer",indicator=True)
## if in both, don't have to do anything
# merged = merged[merged._merge!="both"]
## if in left, add to destination
to_add = merged[merged._merge=="left_only"].id_x.to_list()
to_add_rows = arrays_to_strings(rows_on_tracker[rows_on_tracker.id.isin(to_add)].drop(columns=['id'])).to_dict(orient="records")
response = requests.post(
    "https://baserow.datarescueproject.org/api/database/rows/table/1124/batch/?user_field_names=true",
    headers={
        "Authorization": f"Token {Vol_API}",
        "Content-Type": "application/json"
    },
    json={
        "items":to_add_rows
    }
)
print(response.json())
## if in right, delete from destination
to_delete = merged[merged._merge=="right_only"].id_y.to_list()

response = requests.post(
    "https://baserow.datarescueproject.org/api/database/rows/table/1124/batch-delete/",
    headers={
        "Authorization": f"Token {Vol_API}",
        "Content-Type": "application/json"
    },
    json={
        "items":to_delete
    }
)
print(response.json())

In [89]:
response = requests.post(
    "https://baserow.datarescueproject.org/api/database/rows/table/1124/?user_field_names=true",
    headers={
        "Authorization": f"Token {Vol_API}",
        "Content-Type": "application/json"
    },
    json=rows_to_add_json[0]
    )

In [70]:
import json
print("Status:", response.status_code)
print("Response:", json.dumps(response.json(), indent=2))
print("Payload:", json.dumps(payload, indent=2))

Status: 400
Response: {
  "error": "ERROR_REQUEST_BODY_VALIDATION",
  "detail": {
    "non_field_errors": [
      {
        "error": "Invalid data. Expected a dictionary, but got list.",
        "code": "invalid"
      }
    ]
  }
}

NameError: name 'payload' is not defined

In [24]:
r = requests.get(
    "https://baserow.datarescueproject.org/api/database/fields/table/1124/",
    headers={
        "Authorization": f"Token {Vol_API}",
    }
)

In [26]:
r.json()

[{'id': 10804,
  'table_id': 1124,
  'name': 'Name',
  'order': 0,
  'type': 'text',
  'primary': True,
  'read_only': False,
  'immutable_type': False,
  'immutable_properties': False,
  'description': None,
  'database_id': 320,
  'workspace_id': 182,
  'db_index': False,
  'field_constraints': [],
  'text_default': ''},
 {'id': 10805,
  'table_id': 1124,
  'name': 'Notes',
  'order': 1,
  'type': 'long_text',
  'primary': False,
  'read_only': False,
  'immutable_type': False,
  'immutable_properties': False,
  'description': None,
  'database_id': 320,
  'workspace_id': 182,
  'db_index': False,
  'field_constraints': [],
  'long_text_enable_rich_text': False},
 {'id': 10806,
  'table_id': 1124,
  'name': 'Active',
  'order': 2,
  'type': 'boolean',
  'primary': False,
  'read_only': False,
  'immutable_type': False,
  'immutable_properties': False,
  'description': None,
  'database_id': 320,
  'workspace_id': 182,
  'db_index': False,
  'field_constraints': [],
  'boolean_default': False},
 {'id': 10810,
  'table_id': 1124,
  'name': 'Dataset Claim Status',
  'order': 3,
  'type': 'single_select',
  'primary': False,
  'read_only': False,
  'immutable_type': False,
  'immutable_properties': False,
  'description': None,
  'database_id': 320,
  'workspace_id': 182,
  'db_index': False,
  'field_constraints': [],
  'select_options': [{'id': 5823, 'value': 'claimed', 'color': 'dark-green'},
   {'id': 5824, 'value': 'unclaimed', 'color': 'darker-red'}],
  'single_select_default': None}]